modules-search: [ /usr/lib/felunyx/tests/calamares-failure/modules, /usr/lib/calamares/modules ]
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec: [ partition, mount, unpackfs, machineid, fstab, locale, keyboard, localecfg, users, displaymanager, networkcfg, hwclock, services-systemd, packages, initcpiocfg, initcpio, bootloader, felunyx-fail, umount ]
  - show: [ finished ]
branding: felunyx
prompt-install: true
dont-chroot: false
oem-setup: false
