backend: pacman
skip_if_no_internet: false
update_db: false
update_system: false
operations:
  - remove:
      - felunyx-iso-hooks
  - try_remove:
      - memtest86+
      - memtest86+-efi
      - archinstall
      - clonezilla
      - cloud-init
      - livecd-sounds
