backend: pacman
operations:
  - remove:
      - felunyx-iso-hooks
      - memtest86+
      - memtest86+-efi
  - try_remove:
      - archinstall
      - clonezilla
      - cloud-init
      - livecd-sounds
