efi:
  mountPoint: /boot/efi
  recommendedSize: 1GiB
  minimumSize: 512MiB
  label: EFI
initialPartitioningChoice: none
initialSwapChoice: none
defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: btrfs
availableFileSystemTypes: [ btrfs ]
userSwapChoices: [ none, small, suspend, file ]
allowManualPartitioning: true
enableLuksAutomatedPartitioning: false
