units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "sddm.service"
    action: "enable"
    mandatory: true
  - name: "graphical.target"
    action: "set-default"
    mandatory: true
  - name: "qemu-guest-agent.service"
    action: "enable"
    mandatory: false
  - name: "sshd.service"
    action: "mask"
    mandatory: false
  - name: "sshd.socket"
    action: "mask"
    mandatory: false
  - name: "felunyx-live-setup.service"
    action: "disable"
    mandatory: false
