unpack:
  - source: "/run/archiso/bootmnt/felunyx/x86_64/airootfs.sfs"
    sourcefs: squashfs
    destination: ""
    exclude:
      - "/etc/mkinitcpio.d/linux-zen.preset"
      - "/etc/mkinitcpio.d/linux-lts.preset"
      - "/etc/mkinitcpio.conf.d/archiso.conf"
    weight: 160
  - source: "/etc/calamares/preinstall_copy/etc/mkinitcpio.d/linux-zen.preset"
    sourcefs: file
    destination: "/etc/mkinitcpio.d/linux-zen.preset"
    weight: 1
  - source: "/etc/calamares/preinstall_copy/etc/mkinitcpio.d/linux-lts.preset"
    sourcefs: file
    destination: "/etc/mkinitcpio.d/linux-lts.preset"
    weight: 1
