title    Felunyx OS — Linux LTS fallback (%ARCH%, UEFI)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% console=tty0 console=ttyS0,115200n8 felunyx.phase=2 felunyx.kernel=lts
